language: node_js
node_js:
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn prod
cache:
  yarn: true
  directories:
    - 'node_modules'
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
